version: "2"
services:
  mongodb:
    image: mongo:3.6.6
    ports:
      - 27017:27017
    volumes:
      - ~/data:/data/db
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 5672:5672
      - 15672:15672